// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QL_CoffeeShop_Test.Data;

#nullable disable

namespace QL_CoffeeShop_Test.Migrations
{
    [DbContext(typeof(CoffeeshopDbContext))]
    [Migration("20260511020154_FirstCreate")]
    partial class FirstCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QL_CoffeeShop_Test.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("detail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee-1024x536.webp",
                            IsTrendingProduct = false,
                            Name = "America",
                            Price = 25m,
                            detail = "Name product"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee1024x536.webp",
                            IsTrendingProduct = false,
                            Name = "Vietnam",
                            Price = 20m,
                            detail = "Vietnamese product"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee1024x536.webp",
                            IsTrendingProduct = false,
                            Name = "United Kingdom",
                            Price = 15m,
                            detail = "UK product"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee-1024x536.webp",
                            IsTrendingProduct = false,
                            Name = "India",
                            Price = 15m,
                            detail = "India product"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee1024x536.webp",
                            IsTrendingProduct = false,
                            Name = "Russian",
                            Price = 25m,
                            detail = "Russian product"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee1024x536.webp",
                            IsTrendingProduct = false,
                            Name = "France",
                            Price = 35m,
                            detail = "France product"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
